#!/bin/sh

rootandudevcheck() {
    if [ "$(whoami)" != "root" ]
    then
        export HASRULES="false"
        if test -d /etc/udev/rules.d
        then
            if grep -rl "0fce" /etc/udev/rules.d >/dev/null
            then
                export HASRULES="true"
            fi
        fi
        if test "$HASRULES" = "true"
        then
    		echo "Not running as root but Sony/SonyEriccson Vendor ID found on your udev rules"
       		echo "if Flashing didn't work well, run flashtool as root"
       	else
       		echo "Not running as root and there is no Sony/SonyEriccson Vendor ID on your udev rules"   
       		echo "The user must be granted access to adb/flashmode/fastboot"
       		echo "If you are unsure what to do, run flashtool as root"
       		exit 1
       	fi
    else
        echo "Running as root."
    fi
}

export BASEDIR=$(dirname $0)
export system64=$(uname -m)
export OS=$(uname -s)

cd $BASEDIR


if test "$OS" = "Linux"
then

    rootandudevcheck;
    chmod 755 ./x10flasher_lib/bin2elf
    chmod 755 ./x10flasher_lib/bin2sin
    chmod 755 ./x10flasher_lib/adb.linux.64
    chmod 755 ./x10flasher_lib/fastboot.linux.64
    chmod 755 ./x10flasher_lib/unyaffs.linux.64
    chmod 755 ./x10flasher_lib/adb.linux.32
    chmod 755 ./x10flasher_lib/fastboot.linux.32
    chmod 755 ./x10flasher_lib/unyaffs.linux.32

    if test "${system64}" = "x86_64"
    then
        export JAVA_HOME=./x10flasher_lib/linjre64
    else
        export JAVA_HOME=./x10flasher_lib/linjre32
    fi

    echo "Used java home : ${JAVA_HOME}"

    ISJAVA64=$($JAVA_HOME/bin/java -version 2>&1|grep 64-Bit|wc -l)
    CP=$(ls ./x10flasher_lib/*jar|xargs|tr ' ' ':')

    if test $ISJAVA64 -gt 0
    then
        UDEV=$(ldd x10flasher_lib/linux/lib64/udev/libusbx-1.0.so.0.1.0 |grep found|wc -l)
        if test $UDEV -gt 0
        then
            export LD_LIBRARY_PATH=./x10flasher_lib/linux/lib64/udev1
        else
            export LD_LIBRARY_PATH=./x10flasher_lib/linux/lib64/udev
        fi
        SWT=./x10flasher_lib/swtlin/swt64.jar
    else
        UDEV=$(ldd x10flasher_lib/linux/lib32/udev/libusbx-1.0.so.0.1.0 |grep found|wc -l)
        if test $UDEV -gt 0
        then
            export LD_LIBRARY_PATH=./x10flasher_lib/linux/lib32/udev1
        else
            export LD_LIBRARY_PATH=./x10flasher_lib/linux/lib32/udev
        fi
        SWT=./x10flasher_lib/swtlin/swt32.jar
    fi

    $JAVA_HOME/bin/java -classpath ./x10flasher.jar:${CP}:${SWT} \
                        -Xms128m -Xmx512m -Duser.country=US -Duser.language=en \
                        -Djsse.enableSNIExtension=false gui.Main

else

    if test "${system64}" = "x86_64"
    then
        export JAVA_HOME=./x10flasher_lib/macjre64       
    else
        export JAVA_HOME=./x10flasher_lib/macjre32
    fi

    echo "Used java home : ${JAVA_HOME}"

    chmod 755 ./x10flasher_lib/adb.mac.64
    chmod 755 ./x10flasher_lib/fastboot.mac.64
    chmod 755 ./x10flasher_lib/unyaffs.mac.64
    chmod 755 ./x10flasher_lib/adb.mac.32
    chmod 755 ./x10flasher_lib/fastboot.mac.32
    chmod 755 ./x10flasher_lib/unyaffs.mac.32

    ISJAVA64=$($JAVA_HOME/bin/java -version 2>&1|grep 64-Bit|wc -l)
    CP=$(ls ./x10flasher_lib/*jar|xargs|tr ' ' ':')

    if test $ISJAVA64 -gt 0
    then
        export DYLD_LIBRARY_PATH=./x10flasher_lib/mac/lib64:$DYLD_LIBRARY_PATH
        SWT=./x10flasher_lib/swtmac/swt64.jar
    else
        export DYLD_LIBRARY_PATH=./x10flasher_lib/mac/lib32:$DYLD_LIBRARY_PATH
        SWT=./x10flasher_lib/swtmac/swt32.jar
    fi

    $JAVA_HOME/bin/java -XstartOnFirstThread -classpath ./x10flasher.jar:${CP}:${SWT} \
                        -Xms128m -Xmx512m -Duser.country=US -Duser.language=en \
                        -Djsse.enableSNIExtension=false gui.Main

fi
