/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.flashtool;

import org.testng.annotations.*;

import static org.testng.Assert.*;

import org.flashtool.gui.Main;

public class AppTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
