/dev/sh -c "/data/local/tmp/su -c '/data/local/tmp/busybox mount -o rw,remount /system'"
/dev/sh -c "/data/local/tmp/su -c '/data/local/tmp/busybox cp /data/local/tmp/_su /system/xbin'"
/dev/sh -c "/data/local/tmp/su -c 'chown 0.0 /system/xbin/_su'"
/dev/sh -c "/data/local/tmp/su -c 'chmod 6755 /system/xbin/_su'"
/dev/sh -c "/data/local/tmp/su -c '/data/local/tmp/busybox cp /data/local/tmp/su /system/xbin'"
/dev/sh -c "/data/local/tmp/su -c 'chown 0.0 /system/xbin/su'"
/dev/sh -c "/data/local/tmp/su -c 'chmod 6755 /system/xbin/su'"
/dev/sh -c "/data/local/tmp/su -c '/data/local/tmp/busybox cp /data/local/tmp/Superuser.apk /system/app'"
/dev/sh -c "/data/local/tmp/su -c '/data/local/tmp/busybox mount -o ro,remount /system'"
/dev/sh -c "/data/local/tmp/su -c 'sync'"
/dev/sh -c "/data/local/tmp/su -c 'sync'"
/dev/sh -c "/data/local/tmp/su -c 'sync'"
/dev/sh -c "/data/local/tmp/su -c 'mv /data/app /data/app2'"
/dev/sh -c "/data/local/tmp/su -c 'mv /data/app- /data/app'"
/dev/sh -c "/data/local/tmp/su -c 'mv /data/system /data/system2'"
/dev/sh -c "/data/local/tmp/su -c 'mv /data/system- /data/system'"
/dev/sh -c "/data/local/tmp/su -c 'sync'"
/dev/sh -c "/data/local/tmp/su -c 'sync'"
/dev/sh -c "/data/local/tmp/su -c 'sync'"
